### PR TITLE
Remove mentions of the disused `spork` gem

### PR DESCRIPTION
**Pull request by DanielVartanov**
## Summary

Remove mentioned of the disused `spork` gem.

## Motivation and Context

[spork gem](https://github.com/sporkrb/spork) is now disused, it makes no sense to mention it while running `rails generate cucumber:install --help` and to act upon it.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [ ] I've added tests for my code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by olleolleolle — APPROVED** [review]
I'm in favour of remove support for generating new spork configs.

**Comment by olleolleolle** [comment]
Ah, a linting complaint. @DanielVartanov can you change that? Can we get to green?

**Comment by DanielVartanov** [comment]
@olleolleolle Thanks! Sure, I'll satisfy the linter now

**Comment by DanielVartanov** [comment]
@olleolleolle the build failed because of a known bug in `appraisal`: https://github.com/thoughtbot/appraisal/issues/186
We can either upgrade `appraisal` version or downgrade `rake` version, WDYT?

**Comment by olleolleolle** [comment]
@DanielVartanov Is there a released Appraisal yet? If not, I guess using the fork to see it green is one good way to go. A new release will follow soon anyway.

**Comment by olleolleolle** [comment]
Perhaps a RUBYOPT with -rset?

**Comment by luke-hill** [comment]
This is fixed on `main`.

Thankyou @DanielVartanov Merging now.

**Comment by aslakhellesoy** [comment]
Hi @DanielVartanov,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Comment by DanielVartanov** [comment]
Thank you all!

**Pull request merged**
