### PR TITLE
Add Rails 7.2 to test matrix

### PR DESCRIPTION
**Pull request by p8**
### 🏷️ What kind of change is this?

- :bank: Refactoring/debt/DX (improvement to code design, tooling, etc. without changing behaviour)

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://github.com/cucumber/.github/tree/main?tab=coc-ov-file)

### CODE REVIEW

**Comment by olleolleolle** [comment]
@p8 Awesome, I guess we need to land it in         gemfile: ['rails_5_2', 'rails_6_0', 'rails_6_1', 'rails_7_0', 'rails_7_1']
 too

**Comment by olleolleolle** [comment]
Ah, right, some limits on Ruby/Rails versions for exclude/include

```
Because railties >= 7.2.0.beta1 depends on Ruby >= 3.1.0
  and rails_7_2.gemfile depends on railties ~> 7.2.1,
  Ruby >= 3.1.0 is required.
So, because current Ruby version is = 3.0.7,
  version solving has failed.
```

**Comment by p8** [comment]
@olleolleolle I've added Ruby 3.3 to the matrix as well.

**Comment by olleolleolle** [comment]
@p8 Thank you for this!

**Comment by p8** [comment]
Thanks @olleolleolle !

**Comment by luke-hill** [comment]
Thanks for bringing this to my attention. Per the comments I need to do a bit of cleanup here. I'll get this done soon because it can just go in a patch release with some minor tidies I'll do in the codebase proper

**Pull request merged**
