### PR TITLE
Change in gemspec: railties < 5.1 instead of < 5

### PR DESCRIPTION
**Pull request by olleolleolle**
Here's me trying to get Rails 5 installable.

I tried using the `rails generate cucumber:install` template, which worked.

# Checklist

- [x] looser gemspec demands on Rails to allows Rails 5.0.0 to install
- [x] marketing this change in the README ("Rails 5.x" is supported, or something)
- [x] merge #308 (Set up for rails 5 testing) into this PR
- [ ] make the test `cucumber-rails/features/no_database.feature` pass
  - [ ] `install_cucumber_rails` in `features/step_definitions/cucumber_rails_steps.rb` is where I'm currently struggling, to effectively `gsub_file` (from Thor) to enter new `gem "...", "..."` lines in the test_app's Gemfile
- [x] Appraisal: disable some ruby 1.9.3 jobs from even trying to run Rails 4.x, Rails 5.x (since the mime-data-types library Rails depends on is 2.0+-only. – Perhaps this is tone-deaf in the light of https://github.com/cucumber/cucumber-ruby/pull/959 – but I'm focussing on one failure now, the one that's stopping Rails 5 tests passing)

See #319

### CODE REVIEW

**Comment by jmmastey** [comment]
Tried this and it seems to work for me as well. Recommend updating the README too, which I can do in another PR if anyone prefers.

**Comment by olleolleolle** [comment]
This part about setting up Appraisals to test everything against all versions of Rails... I have not done yet, and #308 has some of that work done.

The readme notes things about that suite:
https://github.com/cucumber/cucumber-rails#running-appraisal-suite

**Comment by mattwynne** [comment]
Thanks @olleolleolle.

Note that the Appraisals stuff is probably not needed - a set of different Gemfiles would be fine, I think.

Is anyone available to merge this and make a release?

**Comment by mattwynne** [comment]
Thanks @jmmastey if the docs are out of date please do send a PR yes.

**Comment by olleolleolle** [comment]
_Current status_: Having locally merged that other branch into this one, I'm warming the room with the airplane sounds of my computer. (And still going.)

```
$ appraisal rails_5_0 rake test
WARN: Unresolved specs during Gem::Specification.reset:
      rake (>= 0)
      thor (>= 0.14.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
>> BUNDLE_GEMFILE=/opt/src/opensource/ruby/cucumber-rails/gemfiles/rails_5_0.gemfile bundle exec rake test
mkdir -p /opt/src/opensource/ruby/cucumber-rails/cucumber.github.com/api/cucumber-rails/ruby/yardoc
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
/Users/olle/.rbenv/versions/2.3.1/bin/ruby -I/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rspec-core-4e616ccd499c/lib:/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rspec-support-287a19e9f35d/lib /Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rspec-core-4e616ccd499c/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
................

Finished in 0.14075 seconds (files took 1.05 seconds to load)
16 examples, 0 failures

/Users/olle/.rbenv/versions/2.3.1/bin/ruby -S bundle exec cucumber
Using the default profile...
.............................................................
```

**Comment by olleolleolle** [comment]
Here's the output of my run

```
Failing Scenarios:
cucumber features/no_database.feature:5 # Scenario: No ActiveRecord and DatabaseCleaner
```

<details>
  <summary>Here is a full paste of the output</summary>

WARN: Unresolved specs during Gem::Specification.reset:
      rake (>= 0)
      thor (>= 0.14.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
>> BUNDLE_GEMFILE=/opt/src/opensource/ruby/cucumber-rails/gemfiles/rails_5_0.gemfile bundle exec rake test
mkdir -p /opt/src/opensource/ruby/cucumber-rails/cucumber.github.com/api/cucumber-rails/ruby/yardoc
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
/Users/olle/.rbenv/versions/2.3.1/bin/ruby -I/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rspec-core-4e616ccd499c/lib:/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rspec-support-287a19e9f35d/lib /Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rspec-core-4e616ccd499c/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
................

Finished in 0.14075 seconds (files took 1.05 seconds to load)
16 examples, 0 failures

/Users/olle/.rbenv/versions/2.3.1/bin/ruby -S bundle exec cucumber
Using the default profile...
.......................................................................................................F...................

(::) failed steps (::)

expected "      create  \n      create  README.md\n      create  Rakefile\n      create  config.ru\n      crea...rsions/2.3.1/bin/bundle:23:in `load'\n/Users/olle/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'\n" to include "There is an error in index"
Diff:
@@ -1,2 +1,238 @@
-There is an error in index
+      create
+      create  README.md
+      create  Rakefile
+      create  config.ru
+      create  .gitignore
+      create  Gemfile
+      create  app
+      create  app/assets/config/manifest.js
+      create  app/assets/javascripts/application.js
+      create  app/assets/javascripts/cable.js
+      create  app/assets/stylesheets/application.css
+      create  app/channels/application_cable/channel.rb
+      create  app/channels/application_cable/connection.rb
+      create  app/controllers/application_controller.rb
+      create  app/helpers/application_helper.rb
+      create  app/jobs/application_job.rb
+      create  app/mailers/application_mailer.rb
+      create  app/models/application_record.rb
+      create  app/views/layouts/application.html.erb
+      create  app/views/layouts/mailer.html.erb
+      create  app/views/layouts/mailer.text.erb
+      create  app/assets/images/.keep
+      create  app/assets/javascripts/channels
+      create  app/assets/javascripts/channels/.keep
+      create  app/controllers/concerns/.keep
+      create  app/models/concerns/.keep
+      create  bin
+      create  bin/bundle
+      create  bin/rails
+      create  bin/rake
+      create  bin/setup
+      create  bin/update
+      create  config
+      create  config/routes.rb
+      create  config/application.rb
+      create  config/environment.rb
+      create  config/secrets.yml
+      create  config/cable.yml
+      create  config/puma.rb
+      create  config/environments
+      create  config/environments/development.rb
+      create  config/environments/production.rb
+      create  config/environments/test.rb
+      create  config/initializers
+      create  config/initializers/application_controller_renderer.rb
+      create  config/initializers/assets.rb
+      create  config/initializers/backtrace_silencers.rb
+      create  config/initializers/cookies_serializer.rb
+      create  config/initializers/cors.rb
+      create  config/initializers/filter_parameter_logging.rb
+      create  config/initializers/inflections.rb
+      create  config/initializers/mime_types.rb
+      create  config/initializers/new_framework_defaults.rb
+      create  config/initializers/session_store.rb
+      create  config/initializers/wrap_parameters.rb
+      create  config/locales
+      create  config/locales/en.yml
+      create  config/boot.rb
+      create  db
+      create  db/seeds.rb
+      create  lib
+      create  lib/tasks
+      create  lib/tasks/.keep
+      create  lib/assets
+      create  lib/assets/.keep
+      create  log
+      create  log/.keep
+      create  public
+      create  public/404.html
+      create  public/422.html
+      create  public/500.html
+      create  public/apple-touch-icon-precomposed.png
+      create  public/apple-touch-icon.png
+      create  public/favicon.ico
+      create  public/robots.txt
+      create  test/fixtures
+      create  test/fixtures/.keep
+      create  test/fixtures/files
+      create  test/fixtures/files/.keep
+      create  test/controllers
+      create  test/controllers/.keep
+      create  test/mailers
+      create  test/mailers/.keep
+      create  test/models
+      create  test/models/.keep
+      create  test/helpers
+      create  test/helpers/.keep
+      create  test/integration
+      create  test/integration/.keep
+      create  test/test_helper.rb
+      create  tmp
+      create  tmp/.keep
+      create  tmp/cache
+      create  tmp/cache/assets
+      create  vendor/assets/javascripts
+      create  vendor/assets/javascripts/.keep
+      create  vendor/assets/stylesheets
+      create  vendor/assets/stylesheets/.keep
+      remove  app/models/application_record.rb
+      remove  config/initializers/cors.rb
+         run  bundle install
+Fetching gem metadata from https://rubygems.org/
+Fetching version metadata from https://rubygems.org/
+Fetching dependency metadata from https://rubygems.org/
+Resolving dependencies...
+Using rake 11.2.2
+Using concurrent-ruby 1.0.2
+Using i18n 0.7.0
+Using minitest 5.9.0
+Using thread_safe 0.3.5
+Using builder 3.2.2
+Using erubis 2.7.0
+Using mini_portile2 2.1.0
+Using pkg-config 1.1.7
+Using rack 2.0.1
+Using nio4r 1.2.1
+Using websocket-extensions 0.1.2
+Using mime-types-data 3.2016.0521
+Using arel 7.0.0
+Using bundler 1.13.0.rc.1
+Using byebug 9.0.5
+Using coffee-script-source 1.10.0
+Using execjs 2.7.0
+Using method_source 0.8.2
+Using thor 0.19.1
+Using debug_inspector 0.0.2
+Using ffi 1.9.10
+Using multi_json 1.12.1
+Using rb-fsevent 0.9.7
+Using puma 3.4.0
+Using sass 3.4.22
+Using tilt 2.0.5
+Using turbolinks-source 5.0.0
+Using tzinfo 1.2.2
+Using nokogiri 1.6.8
+Using rack-test 0.6.3
+Using sprockets 3.6.3
+Using websocket-driver 0.6.4
+Using mime-types 3.1
+Using coffee-script 2.4.1
+Using uglifier 3.0.0
+Using rb-inotify 0.9.7
+Using turbolinks 5.0.0
+Using activesupport 5.0.0
+Using loofah 2.0.3
+Using mail 2.6.4
+Using listen 3.0.8
+Using rails-dom-testing 2.0.1
+Using globalid 0.3.6
+Using activemodel 5.0.0
+Using jbuilder 2.5.0
+Using rails-html-sanitizer 1.0.3
+Using activejob 5.0.0
+Using activerecord 5.0.0
+Using actionview 5.0.0
+Using actionpack 5.0.0
+Using actioncable 5.0.0
+Using actionmailer 5.0.0
+Using railties 5.0.0
+Using sprockets-rails 3.1.1
+Using coffee-rails 4.2.1
+Using jquery-rails 4.1.1
+Using web-console 3.3.0
+Using rails 5.0.0
+Using sass-rails 5.0.5
+Bundle complete! 12 Gemfile dependencies, 60 gems now installed.
+Use `bundle show [gemname]` to see where a bundled gem is installed.
+      create  config/cucumber.yml
+      create  script/cucumber
+       chmod  script/cucumber
+      create  features/step_definitions
+      create  features/step_definitions/.gitkeep
+      create  features/support
+      create  features/support/env.rb
+       exist  lib/tasks
+      create  lib/tasks/cucumber.rake
+/Users/olle/.rbenv/versions/2.3.1/bin/ruby -S bundle exec cucumber --profile default
+undefined method `assets' for #<Rails::Application::Configuration:0x007fb98b17d760>
+Did you mean?  asset_host (NoMethodError)
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/railtie/configuration.rb:95:in `method_missing'
+/opt/src/opensource/ruby/cucumber-rails/tmp/aruba/test_app/config/initializers/assets.rb:4:in `<top (required)>'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `load'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `block in load'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `load'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/engine.rb:648:in `block in load_config_initializer'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/notifications.rb:166:in `instrument'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/engine.rb:647:in `load_config_initializer'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/engine.rb:611:in `each'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/engine.rb:611:in `block in <class:Engine>'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/initializable.rb:30:in `instance_exec'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/initializable.rb:30:in `run'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/initializable.rb:55:in `block in run_initializers'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/initializable.rb:54:in `run_initializers'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/application.rb:352:in `initialize!'
+/opt/src/opensource/ruby/cucumber-rails/lib/cucumber/rails/application.rb:15:in `initialize!'
+/opt/src/opensource/ruby/cucumber-rails/tmp/aruba/test_app/config/environment.rb:5:in `<top (required)>'
+/opt/src/opensource/ruby/cucumber-rails/lib/cucumber/rails.rb:7:in `require'
+/opt/src/opensource/ruby/cucumber-rails/lib/cucumber/rails.rb:7:in `<top (required)>'
+/opt/src/opensource/ruby/cucumber-rails/tmp/aruba/test_app/features/support/env.rb:1:in `require'
+/opt/src/opensource/ruby/cucumber-rails/tmp/aruba/test_app/features/support/env.rb:1:in `<top (required)>'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/rb_support/rb_language.rb:96:in `load'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/rb_support/rb_language.rb:96:in `load_code_file'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:142:in `load_file'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:84:in `block in load_files!'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:83:in `each'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:83:in `load_files!'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:253:in `load_step_definitions'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:61:in `run!'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/cli/main.rb:32:in `execute!'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/bin/cucumber:8:in `<top (required)>'
+/Users/olle/.rbenv/versions/2.3.1/bin/cucumber:23:in `load'
+/Users/olle/.rbenv/versions/2.3.1/bin/cucumber:23:in `<top (required)>'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.0.rc.1/lib/bundler/cli/exec.rb:63:in `load'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.0.rc.1/lib/bundler/cli/exec.rb:63:in `kernel_load'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.0.rc.1/lib/bundler/cli/exec.rb:24:in `run'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.0.rc.1/lib/bundler/cli.rb:315:in `exec'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.0.rc.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.0.rc.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.0.rc.1/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.0.rc.1/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.0.rc.1/lib/bundler/cli.rb:11:in `start'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.0.rc.1/exe/bundle:34:in `block in <top (required)>'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.0.rc.1/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
+/Users/olle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.0.rc.1/exe/bundle:26:in `<top (required)>'
+/Users/olle/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
+/Users/olle/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
 (RSpec::Expectations::ExpectationNotMetError)
features/no_database.feature:65:in `Then it should fail with:'

Failing Scenarios:
cucumber features/no_database.feature:5 # Scenario: No ActiveRecord and DatabaseCleaner

17 scenarios (1 failed, 16 passed)
123 steps (1 failed, 122 passed)
7m25.505s
</details>

**Comment by olleolleolle** [comment]
**Update**: Have gotten past that error, which was about Asset Pipeline gems not being included. So included them in the `bundle exec rails new` bit of the CucumberRailsSteps.

**Comment by olleolleolle** [comment]
**More update:** Too tired, gotta sleep. I have documented the steps up this pyramid in the body of the PR.

**Comment by mattwynne** [comment]
Great effort @olleolleolle!

**Comment by mathieujobin** [comment]
thank you @olleolleolle 

I believe we have everything on master now

**Pull request closed without merging**
