### PR TITLE
relax railties dependencies to allow 5.0.x

### PR DESCRIPTION
**Pull request by mathieujobin**
could we relax the dependencies to allow rails 5.0 ?

### CODE REVIEW

**Comment by mathieujobin** [comment]
Sorry i had not noticed https://github.com/cucumber/cucumber-rails/pull/320 and https://github.com/cucumber/cucumber-rails/pull/308 before starting this

just keep the one you prefer.

funnily I have an app that I upgraded from rails 3.2.22 to 5.0.0.rc1 and all my cucumber pass with cucumber-rails 1.4.3
I could install 1.4.3 because 5.0.0.rc1 is lower than 5.0

so, there should not be many issues making this work

**Comment by mathieujobin** [comment]
just 2 failures to deal with...

```

Failing Scenarios:
cucumber features/choose_javascript_database_strategy.feature:78 # Scenario: Set the strategy to deletion and run a javascript scenario.
cucumber features/no_database.feature:5 # Scenario: No ActiveRecord and DatabaseCleaner
17 scenarios (2 failed, 15 passed)
123 steps (2 failed, 1 skipped, 120 passed)
4m44.285s
```

**Comment by mathieujobin** [comment]
both failures now pass for me locally.
only one left on travis

```
(::) failed steps (::)
expected "bundle exec cucumber" to be successfully executed (RSpec::Expectations::ExpectationNotMetError)
./features/step_definitions/cucumber_rails_steps.rb:84:in `/^I run the cukes$/'
features/choose_javascript_database_strategy.feature:107:in `When I run the cukes'
Failing Scenarios:
cucumber features/choose_javascript_database_strategy.feature:78 # Scenario: Set the strategy to deletion and run a javascript scenario.
17 scenarios (1 failed, 16 passed)
123 steps (1 failed, 1 skipped, 121 passed)
4m1.568s
```

tried with both ruby 2.2.5 and 2.3.1 using the rails5 gemfile i have added

locally 

```
$  c features/choose_javascript_database_strategy.feature features/no_database.feature 
/home/mathieu/.rvm/gems/ruby-2.2.4/gems/rspec-expectations-3.5.0/lib/rspec/expectations/version.rb:5: warning: already initialized constant RSpec::Expectations::Version::STRING
/home/mathieu/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/rspec-expectations-3.5.0/lib/rspec/expectations/version.rb:5: warning: previous definition of STRING was here
Using the default profile...
...............................

4 scenarios (4 passed)
31 steps (31 passed)
1m1.260s
$ 
```

**Comment by Kosmas** [comment]
:+1:

**Comment by mathieujobin** [comment]
I'm not too sure what to do with that last failure. since it pass for me locally.
just let me know. I need to work on something else now 

cheers

**Comment by mathieujobin** [comment]
single failure left pass for me locally? anyone tried to reproduce what is happening on travis ?

**Comment by brauliobo** [comment]
oh please man... this project needs new maintainers??

**Comment by danascheider** [comment]
I'll take a look at this a little later.

**Comment by mattwynne** [comment]
Would you like to help @brauliobo? I don't work on Rails apps anymore but I'm happy to help you get up to speed if you'd like to help out.

**Comment by brauliobo** [comment]
sure @mattwynne, I could help to review some PR and do some releases, although my experience with cucumber is just a rails user

**Comment by mathieujobin** [comment]
let me know if you want me to mark `features/choose_javascript_database_strategy.feature:78` as `@wip` so we can merge this and work this one out as a separate PR

**Comment by mattwynne** [comment]
@brauliobo that would be awesome, thanks! Do you have time to help @mathieujobin get this last scenario to pass (or help him decide to delete it, if that's the right thing to do)

**Comment by mattwynne** [comment]
To help diagnose this, I suggest changing `features/step_definitions/cucumber_rails_steps.rb` around line 84 to report the contents of `all_output` if the expectation on the status code is not met. Right now we know that the `bundle exec cucumber` command failed but we don't know why.

**Comment by mattwynne** [comment]
@mathieujobin I think that's a reasonable idea, but I don't think we can make a release until we've fixed it (or at least we understand what the failure reason is)

**Comment by mathieujobin** [comment]
@mattwynne I am printing `all_output` but nothing is shown... I will try something else...

it would be so much easier if it failed locally....

```
[mathieu@hz550 cucumber-rails]$  bundle exec cucumber
/home/mathieu/.rvm/gems/ruby-2.2.5/gems/rspec-expectations-3.5.0/lib/rspec/expectations/version.rb:5: warning: already initialized constant RSpec::Expectations::Version::STRING
/home/mathieu/.rvm/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/rspec-expectations-3.5.0/lib/rspec/expectations/version.rb:5: warning: previous definition of STRING was here
Using the default profile...
...........................................................................................................................

17 scenarios (17 passed)
123 steps (123 passed)
5m14.214s
[mathieu@hz550 cucumber-rails]$ 
```

**Comment by fschwahn** [comment]
@mathieujobin I think you can add `@announce-output`-tag to the scenario (in features/choose_javascript_database_strategy.feature:78) and it should output everything?

**Comment by fschwahn** [comment]
Ok, sorry, that didn't work for me locally. Do this instead:

```ruby
When /^I run the cukes$/ do
  run_simple('bundle exec cucumber', false)
  puts all_output
end
```

**Comment by fschwahn** [comment]
Thanks @mathieujobin, I can now reproduce the failure locally. It happens with old versions of database_cleaner (I could reproduce it with version 1.0.1, which was released in 2013). The tests pass with all later versions. The error did not happen locally because bundler would pick a later installed  version of database_cleaner when available.

I don't know the reason why database_cleaner < 1.1.0 is incompatible with rails 5, but I think we can just bump the dependency to ">= 1.1.0" - it's only a development dependency anyway. Is that ok @mattwynne ? Maybe the README should contain a note about that? Also, the gemfiles / Appraisals need to be updated, because they contain the line `gem "database_cleaner", "~> 1.0.1"`

**Comment by mathieujobin** [comment]
@fschwahn Excellent find ! thanks for finding this out.
I'm going to update my PR now and the appraisal file as well.

**Comment by fschwahn** [comment]
There's a typo in the Gemfile, it should read `>= 1.1.0` instead of `=> 1.1.0`

**Comment by mathieujobin** [comment]
just repushed

**Comment by fschwahn** [comment]
Ok, tests are green now, last thing which blocks this from being merged is the `bcat` dependency - now I looked a bit into the history, and it seems that it is not used anywhere - it used to be a dependency of aruba, but is not anymore. I guess this is just a leftover? Maybe @mattwynne knows more? I _think_ it's safe to just remove it.

**Comment by mathieujobin** [comment]
tests definitely execute fine without... that's why I left it out of the various gemfiles, removed it from the gemspec, but I left it in the root Gemfile in case it was useful to someone. I thought it was use to generate doc. 

I opened a PR to have its dependency on rack updated
https://github.com/rtomayko/bcat/pull/24

but no response in 19 days...

**Comment by fschwahn** [comment]
It _seems_ to me like the comment is wrong - even in the commit the dependency was added it was not actually used for generating the documentation (or anything at all - https://github.com/cucumber/cucumber-rails/commit/969d6a3d351fd07b14b8e8a65cd066d25e0b8ffb).

**Comment by mathieujobin** [comment]
I did some tests, I am able to generate the doc with yard without bcat.
and I think you are right, in the gemlock file from the commit you pointed out for release 1.0.1
bcat shows as an aruba dependency

i think we can remove it

**Comment by mathieujobin** [comment]
it used to be for Aruba::Reporting
https://github.com/cucumber/aruba/issues/170

removing

**Comment by mathieujobin** [comment]
I'm thinking to squash this into two commits, I don't know which you prefer

**Comment by mathieujobin** [comment]
bcat removed, all tests passed
ready to merge. I think we should release v1.4.4 or v1.5.0 after this merge

**Comment by mathieujobin** [comment]
@fschwahn @mattwynne ready ?

**Comment by fschwahn** [comment]
Looks good to me, but I'm not part of the project, just interested to see this get shipped

**Comment by mathieujobin** [comment]
I'll happily become a maintainer should the current maintainer give me admin access and also the right to push to rubygems.

cheers,

**Comment by Kosmas** [comment]
@mathieujobin I am away at the moment. I'm sure that @mattwynne can give you access to merge and publish.

**Comment by mathieujobin** [comment]
assuming this gets merged and release as-is. I have updated the History and bump the version in this commit. https://github.com/mathieujobin/cucumber-rails/commit/47e9dade1f0ccd1475920bd21340d9136376cabc

I'll adjust the date once we are able to publish it to rubygems.org

**Comment by SoccerGee** [comment]
@mathieujobin have you had a chance to make any progress on getting this merged?

**Comment by mathieujobin** [comment]
this is ready to merge and to publish... 
I am just waiting on someone to give me the required access
as mentioned above, I got the changelog update in a different branch ready

@Kosmas @mattwynne any update on your sides?

**Comment by mattwynne** [comment]
SOOOO sorry for the lag. @mathieujobin I think you now have the keys to the git repo. I'll sort out the deploy bit next.

**Comment by mattwynne** [comment]
@mathieujobin for release karma I need your email. Can you follow the instructions at https://github.com/cucumber/cucumber-rails/blob/master/CONTRIBUTING.md#gaining-release-karma please. I promise I'll try to respond more quickly this time. Ping me in gitter.im if you want - that makes my phone beep!

**Comment by brauliobo** [comment]
thanks!!

**Comment by mathieujobin** [comment]
rubygems should have the gem pushed within couple of hours

**Comment by olleolleolle** [comment]
So much love for this work being done!

**Comment by mattwynne** [comment]
👏  for @mathieujobin for stepping up to become a new member of the cucumber-rails maintainers. cc @cucumber/developers let's give him a warm welcome.

**Comment by subhashb** [comment]
👍 👏  Thank you so much!

**Pull request merged**
