### PR TITLE
Cut v1.8

### PR DESCRIPTION
**Pull request by luke-hill**
Release v1.8

### CODE REVIEW

**Comment by olleolleolle** [comment]
@luke-hill Can you release the gem to RubyGems too?

**Comment by luke-hill** [comment]
I think @xtrasimplicity needs to do this. I don't have push capabilities. I'll message some people on slack about this though

**Comment by xtrasimplicity** [comment]
I'll do that in a few mins. @luke-hill

**Comment by xtrasimplicity** [comment]
@luke-hill Done. It's about 1/10th of the size of the last release - is that to be expected?
https://rubygems.org/gems/cucumber-rails/versions/1.8.0

**Comment by luke-hill** [comment]
Unsure.

It could be a rubygems packaging thing perhaps?

https://github.com/cucumber/cucumber-rails/compare/v1.7.0..v1.8.0 the diff shows a net reduction in code, but most of that isn't library code it's yml from rubocop

I do know changing some of the verbose globals will save a "bit" of space. But I'm not 100% sure.

Maybe try rebuilding the 1.7 gem and check the size again? It does sound a bit worrying. Could also check another instance of the 1.8 gem?

**Comment by luke-hill** [comment]
EDIT: False alarm. Nothing to worry about. I've removed 9/10ths of the crud.

We had a couple of physical gems that were bundled as part of the cucumber-rails gem. Now they no longer are!

**Comment by xtrasimplicity** [comment]
Awesome! Great work! :)

**Pull request merged**
