### PR TITLE
[WIP] Resolved test failures

### PR DESCRIPTION
**Pull request by xtrasimplicity**
Resolving https://github.com/cucumber/cucumber-rails/issues/354

### CODE REVIEW

**Comment by olleolleolle** [comment]
(Thanks for working on this!)

**Comment by xtrasimplicity** [comment]
@olleolleolle Not a problem. It looks like it's still a little messed up, so I might need to go back to the drawing board a little. I have a strong feeling it is entirely due to gem versions.

**Comment by xtrasimplicity** [comment]
So it turns out I wasn't entirely correct. For some reason, running `bundle exec rails g scaffold` would attempt to run the cucumber tests, which would subsequently fail and return a non-zero exit code, failing the features.

Removing `successfully` from the `And I successfully run ...` steps resolves the issues in Ruby 2.4. This may not be ideal, but given the assertions are still valid I don't think it's such a big deal at the moment. At least this way we'll have passing tests. :)

**Comment by xtrasimplicity** [comment]
So far,  the tests are passing for ruby versions 2.1.10 and up, but not for 2.0.0, due to the following error:
````
expected "private method include' called for ActionDispatch::Assertions:Module (NoMethodError)
/home/travis/.rvm/gems/ruby-2.0.0-p648/gems/turbolinks-5.1.0/lib/turbolinks.rb:25:in block (2 levels) in <class:Engine>'
/home/travis/.rvm/gems/ruby-2.0.0-p648/gems/activesupport-4.0.13/lib/active_support/lazy_load_hooks.rb:38:in instance_eval'
/home/travis/.rvm/gems/ruby-2.0.0-p648/gems/activesupport-4.0.13/lib/active_support/lazy_load_hooks.rb:38:in execute_hook'
/home/travis/.rvm/gems/ruby-2.0.0-p648/gems/activesupport-4.0.13/lib/active_support/lazy_load_hooks.rb:45:in block in run_load_hooks'
/home/travis/.rvm/gems/ruby-2.0.0-p648/gems/activesupport-4.0.13/lib/active_support/lazy_load_hooks.rb:44:in each'
/home/travis/.rvm/gems/ruby-2.0.0-p648/gems/activesupport-4.0.13/lib/active_support/lazy_load_hooks.rb:44:in run_load_hooks'
/home/travis/.rvm/gems/ruby-2.0.0-p648/gems/actionpack-4.0.13/lib/action_controller/base.rb:257:in <class:Base>'
/home/travis/.rvm/gems/ruby-2.0.0-p648/gems/actionpack-4.0.13/lib/action_controller/base.rb:163:in <module:ActionController>'
/home/travis/.rvm/gems/ruby-2.0.0-p648/gems/actionpack-4.0.13/lib/action_controller/base.rb:4:in <top (required)>'
/home/travis/build/cucumber/cucumber-rails/lib/cucumber/rails/action_controller.rb:1:in <top (required)>'
/home/travis/.rvm/gems/ruby-2.0.0-p648/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in require'
/home/travis/.rvm/gems/ruby-2.0.0-p648/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in block in require'
/home/travis/.rvm/gems/ruby-2.0.0-p648/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:214:in load_dependency'
/home/travis/.rvm/gems/ruby-2.0.0-p648/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in require'
/home/travis/build/cucumber/cucumber-rails/lib/cucumber/rails.rb:8:in <top (required)>'
/home/travis/build/cucumber/cucumber-rails/tmp/aruba/rails-3-app/features/support/env.rb:7:in require'
/home/travis/build/cucumber/cucumber-rails/tmp/aruba/rails-3-app/features/support/env.rb:7:in <top (required)>'
/home/travis/.rvm/gems/ruby-2.0.0-p648/gems/cucumber-1.3.20/lib/cucumber/rb_support/rb_language.rb:95:in load'
/home/travis/.rvm/gems/ruby-2.0.0-p648/gems/cucumber-1.3.20/lib/cucumber/rb_support/rb_language.rb:95:in load_code_file'
/home/travis/.rvm/gems/ruby-2.0.0-p648/gems/cucumber-1.3.20/lib/cucumber/runtime/support_code.rb:180:in load_file'
/home/travis/.rvm/gems/ruby-2.0.0-p648/gems/cucumber-1.3.20/lib/cucumber/runtime/support_code.rb:83:in block in load_files!'
/home/travis/.rvm/gems/ruby-2.0.0-p648/gems/cucumber-1.3.20/lib/cucumber/runtime/support_code.rb:82:in each'
/home/travis/.rvm/gems/ruby-2.0.0-p648/gems/cucumber-1.3.20/lib/cucumber/runtime/support_code.rb:82:in load_files!'
/home/travis/.rvm/gems/ruby-2.0.0-p648/gems/cucumber-1.3.20/lib/cucumber/runtime.rb:184:in load_step_definitions'
/home/travis/.rvm/gems/ruby-2.0.0-p648/gems/cucumber-1.3.20/lib/cucumber/runtime.rb:42:in run!'
/home/travis/.rvm/gems/ruby-2.0.0-p648/gems/cucumber-1.3.20/lib/cucumber/cli/main.rb:47:in execute!'
/home/travis/.rvm/gems/ruby-2.0.0-p648/gems/cucumber-1.3.20/bin/cucumber:13:in <top (required)>'
/home/travis/.rvm/gems/ruby-2.0.0-p648/bin/cucumber:23:in load'
/home/travis/.rvm/gems/ruby-2.0.0-p648/bin/cucumber:23:in <main>'
/home/travis/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in eval'
/home/travis/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in <main>'" to have output string includes: "1 scenario (1 failed)
1 step (1 failed)"
````

@olleolleolle , @aslakhellesoy Would it be possible for us to cease official support for Ruby 2.0.0? If so, I can remove 2.0.0 from the `.travis-ci.yml` file and we'll be able to have a test suite that passes. :)

**Comment by xtrasimplicity** [comment]
I'm currently working on re-adding Ruby 2.0.0 support. Let's hold off on Merging for the moment. :)

**Comment by xtrasimplicity** [comment]
I ended up monkey patching the `ActionDispatch::Assertions` module so that calls to the _private_ method `include` won't raise exceptions on Ruby 2.0.0 (and instead will trigger `ActionDispatch::Assertions.send(:include)`).

The tests now pass for Ruby 2.0.0, along with the other versions. Are you happy for me to merge this into Master?

**Comment by Kosmas** [comment]
👍

**Comment by Kosmas** [comment]
👍 @xtrasimplicity that is great. Yes you can merge to master. Thanks!

**Comment by xtrasimplicity** [comment]
Reopening as Rails 4.0 and 4.2 have failed on Ruby 2.1.0. I haven't been able to reproduce this on my development environment, nor on a Ubuntu 14.04 vagrant box. Strangely, the code on `xtrasimplicity:bug_fix/TestsFailing` and `cucumber:master` are identical, and the tests were successful prior to merging the PR. Restarting the failing jobs results in it failing again, so it is definitely reproduceable.

I'll take a look into this again tomorrow, but I'd welcome any suggestions. :)

**Comment by dlibanori** [comment]
@xtrasimplicity may you remove `[WIP]` mark?

**Comment by mvz** [comment]
@dlibanori done!

**Pull request merged**
