### PR TITLE
Fix testing

### PR DESCRIPTION
**Pull request by mvz**
Specs and features are green with these changes when using the main Gemfile. Hopefully it will make the other variations green as well.

### CODE REVIEW

**Comment by mattwynne** [comment]
:tada: Thank you!

**Comment by mattwynne** [comment]
@mvz we're looking for more maintainers on this project. Are you interested in having the commit bit?

**Comment by mvz** [comment]
@mattwynne Yes, I'm definitely interested. Thanks!

**Comment by mvz** [comment]
@mattwynne It's green! :tada:

**Comment by Kosmas** [comment]
@mvz well done! 
I'm sure @mattwynne will give you access so you can merge your changes.

**Comment by mattwynne** [comment]
I've given you the commit bit @mvz, welcome to the team!

**Comment by mvz** [comment]
@mattwynne awesome, thanks!

**Pull request merged**
