### PR TITLE
Add support for Rails 6.0.0.beta1

### PR DESCRIPTION
**Pull request by kotovalexarian**
## Motivation and Context

I want to try Rails 6.0.0.beta1, but the gem `cucumber-rails` doesn't support it, so I added the support.

## How Has This Been Tested?

Rails 6.0.0.beta1 was added to Appraisal, so the whole test suite will run with it in CI.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [ ] I've added tests for my code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by luke-hill** [comment]
EDIT: For other reviewers I didn't ask for a change to docs as realistically I don't think we should be promoting this yet, at least whilst the likelihood for failures and errors is high

**Comment by olleolleolle** [comment]
Good CI work all around!

**Comment by kotovalexarian** [comment]
CI failed, but in my repository it passes:
https://travis-ci.org/libertarian-party/cucumber-rails/builds/485775168

**Comment by olleolleolle** [comment]
LGTM!

**Comment by aslakhellesoy** [comment]
Hi @kotovalexarian,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Comment by luke-hill** [comment]
Merged. Thanks for your contribution!

**Pull request merged**
