### PR TITLE
Conform the new syntax for tag expression

### PR DESCRIPTION
**Pull request by mirelon**

### CODE REVIEW

**Comment by mirelon** [comment]
This pull request fixes #346

**Comment by bramski** [comment]
Poke. Please fix.

**Comment by abraham** [comment]
@mirelon can you take a look at fixing the tests.

**Comment by mirelon** [comment]
I would appreciate help with fixing the tests. I do not understand why they fail - the CI output is not helpful. I just use this branch in order to hide the warning.

**Comment by MonsieurDart** [comment]
Are we sure that those tests were ok before @mirelon changes?

**Comment by abraham** [comment]
It looks like the most recent successful test on this project was five months ago so it may not be your changes.

https://travis-ci.org/cucumber/cucumber-rails/builds

**Comment by xtrasimplicity** [comment]
@abraham It looks like you're right. Is anyone working on fixing the tests on the master branch? If not, I can take a look this weekend.

**Comment by xtrasimplicity** [comment]
Tests are all fixed. @mirelon, did you want to try pulling the latest changes from master and rebasing?

**Comment by aslakhellesoy** [comment]
Hi @mirelon,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Comment by xtrasimplicity** [comment]
Ahh, this test suite gets a little frustrating! @mirelon The tests passed on my local test environment (Ruby 2.0.0 & Ruby 2.1.1, both on Ubuntu 14.04 -- as per the CI environment), but are failing on Travis CI.

I've improved the verbosity of the test failures, to make it more obvious what is happening. It looks like the database cleaner is having issues when not using the old form of tag negation (~): https://travis-ci.org/cucumber/cucumber-rails/jobs/340388467

@olleolleolle Alternatively, we can cease officially supporting ruby 2.0.0?
Any ideas? In the meantime, I'm going to [revert this change](https://github.com/cucumber/cucumber-rails/pull/358).

**Pull request merged**
