### PR TITLE
CI: Upgrade geckodriver-helper

### PR DESCRIPTION
**Pull request by xtrasimplicity**
## Summary
Following on from #370, @radar's improvements to `geckodriver-helper` were merged upstream and released as version `0.20.1`, so I've upgraded the appraisals to match `~> 0.20.2` (the newest release as of today) rather than `~> 0.0.5`.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [ ] I've added tests for my code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

---
This change is [Reviewable](https://reviewable.io/reviews/cucumber/cucumber-rails/389)

### CODE REVIEW

**Comment by xtrasimplicity** [comment]
@olleolleolle Just waiting for Travis to finish. There's a 90%+ chance it'll be fine, given it's pretty much all passing on Ruby 2.2.9, but I'd rather wait. I can see that the codeship build has finished, but I don't seem to have access to view the results. :/

**Comment by olleolleolle** [comment]
I had some "banner vision" re: only 1 of the badges is actually Travis.

**Comment by xtrasimplicity** [comment]
All good! 😀

**Comment by luke-hill** [comment]
For ref, `webdrivers` will manage all path requirements (Not just gecko), if you wanted something more robust. Also exporting the path is possible in travis and would be easier than using a gem?

**Comment by xtrasimplicity** [comment]
@luke-hill Thanks so much for the suggestion - it sounds great! I'll check it out when I get a moment. :+1:

**Pull request merged**
