### PR TITLE
Support rails 7.1

### PR DESCRIPTION
**Pull request by mgrunberg**
### 🤔 What's changed?

Use symbols to set `show_exceptions` in Rails 7.1+ and run test against Rails 7.1

### ⚡️ What's your motivation? 

I get a deprecation warning about the usage of a boolean with `show_exceptions`

### 🏷️ What kind of change is this?

- :bug: Bug fix (non-breaking change which fixes a defect)

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)
- [x] I've changed the behaviour of the code
  - [ ] I have added/updated tests to cover my changes.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [ ] Users should know about my change
  - [ ] I have added an entry to the "Unreleased" section of the [**CHANGELOG**](../blob/main/CHANGELOG.md), linking to this pull request.

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/PULL_REQUEST_TEMPLATE.md)*

### CODE REVIEW

**Review by olleolleolle — APPROVED** [review]
These are carefully-worded, nice changes!

**Comment by luke-hill** [comment]
Can we add a changelog entry for this please as it's quite a big change @mgrunberg

**Comment by luke-hill** [comment]
I'm looking to release v3 proper soon. We got about 1/2 to 2/3rds of the stuff in the rc1 release. There was only 2 big things I wanted to do else. One is on a branch I asked a couple of people to look at.

Also I want to try leave the rc1 out for a bit to ensure nothing is completely goosed there.

**Comment by mgrunberg** [comment]
@luke-hill is now a good time for 3.0.0.rc.2?
About a proper v3 release, you mention two big things pending. Let me know how I can help with those.

**Pull request merged**
