### PR TITLE
Set up build for rails 5 testing

### PR DESCRIPTION
**Pull request by tooky**
Still work in progress, but we can get ready for the rails 5 release here.

### CODE REVIEW

**Comment by Kosmas** [comment]
@tooky so is it OK in Codeship but not in Travis?

**Comment by tooky** [comment]
I'm not sure where codeship camed from @Kosmas?

**Comment by Kosmas** [comment]
@tooky do you want to try and sort the Travis build out, or should I go ahead with the release?

**Comment by tooky** [comment]
Don't let this PR hold up the release. It's WIP for when rails 5 is released!

**Comment by Kosmas** [comment]
@tooky OK. Just released 1.4.3

**Comment by tooky** [comment]
\o/

**Comment by mathieujobin** [comment]
thank you @tooky

**Pull request closed without merging**
