### PR TITLE
Try cucumber 3.0.0.pre.1

### PR DESCRIPTION
**Pull request by tooky**
Creating this PR to check any issues arising with Cucumber 3.0.0.pre.1.

### CODE REVIEW

**Comment by Kosmas** [comment]
@tooky looks good. 
OK to merge?

**Comment by tooky** [comment]
@Kosmas I'm going to make a commit bumping the allowed version in the gemspec on master, incrementing the version of cucumber-rails, and reference this build there. I don't think we need to add the appraisals specifically for this to master? We can then release this in advance of cucumber 3.0, and it will allow people to use 3.0.0.pre.1 in their rails projects. WDYT?

**Comment by Kosmas** [comment]
@tooky that is fine. 
Let me know when you want me to merge and then release the 1.4.5.

**Comment by Kosmas** [comment]
@tooky version 1.4.5 with your changes released.

**Pull request closed without merging**
