### PR TITLE
Update template to stop deprecation warnings

### PR DESCRIPTION
**Pull request by ctreptow**
Fixes deprecation warnings like:

`Deprecated: Found tags option '~@wip'. Support for '~@tag' will be removed from the next release of Cucumber. Please use 'not @tag' instead.`

### CODE REVIEW

**Comment by ctreptow** [comment]
I've never contributed to a project before, so if I'm doing something wrong let me know.  Guidance is welcomed!

**Comment by Kosmas** [comment]
@ctreptow thank you.
There are some automated tests that run on Travis, and we merge the PR if the tests are all passing.
Could you please try to get them to pass, ie run your branch in Travis, and when they pass do the PR.

**Comment by ctreptow** [comment]
Ok, I'll close this until I see green.  Thanks!

**Comment by aslakhellesoy** [comment]
Don't close failing pull requests. Just push new commits until it's green.

**Pull request closed without merging**
